[package]
name = "everest"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
rustyline = "13.0.0"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
